version: "3"
services:
  sqlapp:
    image: sql-app:1.0
    container_name: sql-app
    depends_on:
      - vault
      - mssql
      - myubuntu
    environment:
      DB_SERVER: mssql_vault_server_demo
      DB_DATABASE: Test_database
      DB_SA_USER: sa
      DB_SA_PASSWORD: MyStrongPassword10
      VAULT_ADDR: http://vault_server_demo:8200
      VAULT_TOKEN: '123'
  myubuntu:
    image: my_ubuntu:1.2
    container_name: my_ubuntu
    depends_on:
      - vault
      - mssql
    volumes:
      - ./ubuntu_init:/usr/local/bin/ubuntu_init
    secrets:
      - VAULT_CLUSTER_INFO
    environment:
      VAULT_ADDR: http://vault_server_demo:8200
      VAULT_TOKEN: '123'
      SQL_USER: sa
      MSSQL_SA_PASSWORD: MyStrongPassword10
    command: /bin/bash -c "/usr/local/bin/ubuntu_init/ubuntu_init.sh"
  vault:
    image: hashicorp/vault:1.16
    container_name: vault_server_demo
    ports:
      - "8200:8200/tcp"
    #volumes:
    #  - ./vaultConfig:/vault/config # Bind mount for configuration
    #  - vault_data_volume:/vault/file # Named volume for Vault data
    environment:
      #VAULT_LOCAL_CONFIG: /vault/config/vault-config.json
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    entrypoint: "vault server -dev -dev-root-token-id=123 -dev-listen-address=0.0.0.0:8200"
    restart: unless-stopped
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_vault_server_demo
    user: root
    environment:
      MSSQL_SA_PASSWORD: MyStrongPassword10
      ACCEPT_EULA: "Y"
      MSSQL_PID: Evaluation
    depends_on:
      - vault
    ports:
      - 1433:1433
      - 1434:1434/udp
    secrets:
      - mssql_sa_password
    volumes:
      - vault-mssql-data-2022:/var/opt/mssql/data
volumes:
  vault-mssql-data-2022:
    driver: local
  #vault_data_volume:

secrets:
  VAULT_CLUSTER_INFO:
    file: ./.secrets/VAULT_CLUSTER_INFO.json
  mssql_sa_password:
    file: ./.secrets/mssql_sa_password.txt
