version: "3"
services:
  sqlapp:
    image: ghcr.io/igallion/sql-app:main
    pull_policy: always
    container_name: sql-app
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://vault_server_demo:8200/v1/sys/health?standbyok=true"]
      interval: 10s
      timeout: 5s
      retries: 6
    deploy:
      restart_policy:
        condition: any
        delay: 10s
    ports:
      - "80:80/tcp"
    depends_on:
      vault: 
        condition: service_started
      mssql:
        condition: service_healthy
      myubuntu:
        condition: service_started
    environment:
      DB_SA_USER: sa
      DB_SA_PASSWORD: MyStrongPassword10
      VAULT_ADDR: http://vault_server_demo:8200
      VAULT_USER: appuserdev
      VAULT_PASS: changeme
  myubuntu:
    image: my_ubuntu:1.2
    container_name: my_ubuntu
    depends_on:
      - vault
      - mssql
    environment:
      VAULT_ADDR: http://vault_server_demo:8200
      VAULT_TOKEN: '123'
      SQL_USER: sa
      MSSQL_SA_PASSWORD: MyStrongPassword10
    command: /bin/bash -c "/usr/local/bin/ubuntu_init/ubuntu_init.sh"
  vault:
    image: hashicorp/vault:1.20
    container_name: vault_server_demo
    ports:
      - "8200:8200/tcp"
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-config.hcl:/vault/config.d/vault-config.hcl
    depends_on:
      mssql:
        condition: service_healthy   
    entrypoint: "vault server -dev -dev-root-token-id=123 -dev-listen-address=0.0.0.0:8200"
    restart: unless-stopped
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    pull_policy: always
    container_name: mssql_vault_server_demo
    user: root
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -Usa -PMyStrongPassword10 -C -Q 'select 1'"]
      interval: 1s
      timeout: 30s
      retries: 20
    environment:
      MSSQL_SA_PASSWORD: MyStrongPassword10
      ACCEPT_EULA: "Y"
      MSSQL_PID: Evaluation
    ports:
      - 1433:1433
      - 1434:1434/udp
  prometheus:
    image: my_prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
secrets:
  VAULT_USER:
    file: .secrets/VAULT_USER.txt
  VAULT_PASS:
    file: .secrets/VAULT_PASS.txt
  MSSQL_SA_PASSWORD:
    file: .secrets/MSSQL_SA_PASSWORD.txt