version: "3"
services:
  sqlapp:
    image: ghcr.io/igallion/sql-app:main
    container_name: sql-app
    ports:
      - "80:80/tcp"
    depends_on:
      - vault
      - mssql
      - myubuntu
    environment:
      DB_SA_USER: sa
      DB_SA_PASSWORD: MyStrongPassword10
      VAULT_ADDR: http://vault_server_demo:8200
      VAULT_USER: appuserdev
      VAULT_PASS: changeme
  myubuntu:
    image: my_ubuntu:1.2
    container_name: my_ubuntu
    depends_on:
      - vault
      - mssql
    environment:
      VAULT_ADDR: http://vault_server_demo:8200
      VAULT_TOKEN: '123'
      SQL_USER: sa
      MSSQL_SA_PASSWORD: MyStrongPassword10
    command: /bin/bash -c "/usr/local/bin/ubuntu_init/ubuntu_init.sh"
  vault:
    image: hashicorp/vault:1.20
    container_name: vault_server_demo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/v1/sys/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "8200:8200/tcp"
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    entrypoint: "vault server -dev -dev-root-token-id=123 -dev-listen-address=0.0.0.0:8200"
    restart: unless-stopped
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_vault_server_demo
    user: root
    environment:
      MSSQL_SA_PASSWORD: MyStrongPassword10
      ACCEPT_EULA: "Y"
      MSSQL_PID: Evaluation
    depends_on:
      - vault
    ports:
      - 1433:1433
      - 1434:1434/udp
