apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault_deployment
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:1.15
          ports:
            - containerPort: 8200
          command:
            ["vault", "server", "-config=/vault/config/vault-config.json"]
          env:
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: flask_blog_config
                  key: vault-addr
            - name: VAULT_LOCAL_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: flask_blog_config
                  key: vault-config
---
apiVersion: v1
kind: Service
metadata:
  name: vault-service
spec:
  selector:
    app: vault
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
