import cx_Oracle

# Replace these variables with your database connection details
#sqlplus sqlplus sys/MyStrongPassword10@localhost:1521/FREEPDB1 as sysdba
username = 'sys'
password = 'MyStrongPassword10'
dsn = '192.168.0.237:1521/FREEPDB1'  # This is the Data Source Name or TNS (e.g., 'hostname:port/service_name')

try:
    # Establish the database connection
    connection = cx_Oracle.connect(username, password, dsn, mode=cx_Oracle.SYSDBA)
    print("Successfully connected to the database")

      # Create a cursor
    cursor = connection.cursor()

    # Create a table
    create_table_query = """
    CREATE TABLE test_table (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR2(50),
        age NUMBER,
        PRIMARY KEY (id)
    )
    """
    #cursor.execute(create_table_query)
    print("Table created successfully")

    # Insert a record into the table
    insert_query = "INSERT INTO test_table (name, age) VALUES (:name, :age)"
    cursor.execute(insert_query, {'name': 'John Doe', 'age': 30})
    print("Record inserted successfully")

    # Commit the transaction
    connection.commit()
    print("Transaction committed successfully")

    # Create a cursor
    cursor = connection.cursor()

    # Execute a sample query
    cursor.execute("SELECT * FROM test_table")
    rows = cursor.fetchall()
    # Fetch and print the results
    print(rows)
    print("Listing location table")
    for row in rows:
        print(row)

except cx_Oracle.DatabaseError as e:
    print(f"Database connection error: {e}")

finally:
    # Close the cursor and connection
    if cursor:
        cursor.close()
    if connection:
        connection.close()
